In [67]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [68]:
pip install ucimlrepo

In [69]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
spambase = fetch_ucirepo(id=94)

# data (as pandas dataframes)
X = spambase.data.features
y = spambase.data.targets

# metadata
print(spambase.metadata)

# variable information
print(spambase.variables)


{'uci_id': 94, 'name': 'Spambase', 'repository_url': 'https://archive.ics.uci.edu/dataset/94/spambase', 'data_url': 'https://archive.ics.uci.edu/static/public/94/data.csv', 'abstract': 'Classifying Email as Spam or Non-Spam', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 4601, 'num_features': 57, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1999, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C53G6X', 'creators': ['Mark Hopkins', 'Erik Reeber', 'George Forman', 'Jaap Suermondt'], 'intro_paper': None, 'additional_info': {'summary': 'The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...\n\nThe classification task for this dataset is to determine whether a given email is spam or not.\n\t\nOur collecti

In [70]:
features = X
target = y

In [71]:
scaler = StandardScaler()
scaler.fit(features)
standardized_data = scaler.transform(features)

In [72]:
features = standardized_data
target = y

In [73]:
X_train, X_test, Y_train, Y_test = train_test_split(features,target, test_size = 0.2, random_state=2)


In [74]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [75]:
spam_lr_library = LogisticRegression()
spam_lr_library.fit(X_train, Y_train)
X_test_prediction = spam_lr_library.predict(X_test)
X_train_prediction = spam_lr_library.predict(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [91]:
#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score for training data predictions
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)

# F1 Score for test data predictions
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall for training data predictions
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)

# recall for test data predictions
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision for training data predictions
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)

# precision for test data predictions
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy on training data
X_train_prediction = spam_lr_library.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)

print('Accuracy on Training data using logistic regression : ', round(training_data_accuracy*100, 2), '%')

# accuracy on test data
X_test_prediction = spam_lr_library.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[527  18]
 [ 49 327]]
Training data Precision = 0.9266187050359712
Test data Precision = 0.9478260869565217
0.9317934782608696
Accuracy on Training data using logistic regression :  93.18 %
0.9272529858849077
Accuracy on Test data :  92.73 %


In [77]:
from sklearn.svm import SVC
spam_svm_library = SVC(kernel='linear')
spam_svm_library.fit(X_train, Y_train)
X_test_prediction = spam_svm_library.predict(X_test)
X_train_prediction = spam_svm_library.predict(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [92]:
#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score for training data predictions
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)

# F1 Score for test data predictions
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall for training data predictions
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)

# recall for test data predictions
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision for training data predictions
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)

# precision for test data predictions
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy on training data
X_train_prediction = spam_svm_library.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)

print('Accuracy on Training data  using svc: ', round(training_data_accuracy*100, 2), '%')

# accuracy on test data
X_test_prediction = spam_svm_library.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[527  18]
 [ 49 327]]
Training data F1 Score = 0.9112133003183588
Test data F1 Score = 0.8696808510638298
Training data Recall = 0.8963117606123869
Test data Recall = 0.8696808510638298
Training data Precision = 0.9266187050359712
Test data Precision = 0.9478260869565217
0.935054347826087
Accuracy on Training data  using svc:  93.51 %
0.9283387622149837
Accuracy on Test data :  92.83 %


In [79]:
from sklearn.naive_bayes import GaussianNB

In [80]:
spam_nb_library = GaussianNB()
spam_nb_library.fit(X_train, Y_train)
X_test_prediction = spam_nb_library.predict(X_test)
X_train_prediction = spam_nb_library.predict(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [93]:
#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score for training data predictions
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)

# F1 Score for test data predictions
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall for training data predictions
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)

# recall for test data predictions
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision for training data predictions
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)

# precision for test data predictions
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy on training data
X_train_prediction = spam_nb_library.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)

print('Accuracy on Training data using naive bayes : ', round(training_data_accuracy*100, 2), '%')

# accuracy on test data
X_test_prediction = spam_nb_library.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[524  21]
 [ 45 331]]
Training data F1 Score = 0.9158154279675943
Test data F1 Score = 0.8803191489361702
Training data Recall = 0.9046624913013221
Test data Recall = 0.8803191489361702
Training data Precision = 0.927246790299572
Test data Precision = 0.9403409090909091
0.8092391304347826
Accuracy on Training data using naive bayes :  80.92 %
0.8295331161780674
Accuracy on Test data :  82.95 %


from comparing th eaccuracy of all SVC has more accuracy so it is better algorithm

**Without using Libraries**

In [82]:
class Logistic_Regression():
  def __init__(self, learning_rate, no_of_iterations):

    self.learning_rate = learning_rate
    self.no_of_iterations = no_of_iterations

  def fit(self, X, Y):
    self.m, self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y.values.ravel()

    for i in range(self.no_of_iterations):
      self.update_weights()
  def update_weights(self):

    Y_hat = 1 / (1 + np.exp( - (self.X.dot(self.w) + self.b ) ))

    dw = (1/self.m)*np.dot(self.X.T, (Y_hat - self.Y))
    db = (1/self.m)*np.sum(Y_hat - self.Y)

    self.w = self.w - self.learning_rate * dw
    self.b = self.b - self.learning_rate * db

  def predict(self, X):
    Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b ) ))
    Y_pred = np.where( Y_pred > 0.5, 1, 0)
    return Y_pred


In [83]:
spam_lr = Logistic_Regression(learning_rate=0.01, no_of_iterations=1000)
spam_lr.fit(X_train, Y_train)
X_test_prediction = spam_lr.predict(X_test)
X_train_prediction = spam_lr.predict(X_train)

In [84]:
#confusion matrix
cf_matrix = confusion_matrix(Y_test, X_test_prediction)
print(cf_matrix)

# F1 score for training data predictions
f1_score_train = f1_score(Y_train, X_train_prediction)
print('Training data F1 Score =', f1_score_train)

# F1 Score for test data predictions
f1_score_test = recall_score(Y_test, X_test_prediction)
print('Test data F1 Score =', f1_score_test)

# recall for training data predictions
recall_train = recall_score(Y_train, X_train_prediction)
print('Training data Recall =', recall_train)

# recall for test data predictions
recall_test = recall_score(Y_test, X_test_prediction)
print('Test data Recall =', recall_test)

# precision for training data predictions
precision_train = precision_score(Y_train, X_train_prediction)
print('Training data Precision =', precision_train)

# precision for test data predictions
precision_test = precision_score(Y_test, X_test_prediction)
print('Test data Precision =', precision_test)

# accuracy on training data
X_train_prediction = spam_lr.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(training_data_accuracy)

print('Accuracy on Training data : ', round(training_data_accuracy*100, 2), '%')

# accuracy on test data
X_test_prediction = spam_lr.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print(test_data_accuracy)
print('Accuracy on Test data : ', round(test_data_accuracy*100, 2), '%')

[[520  25]
 [ 63 313]]
Training data F1 Score = 0.8809523809523809
Test data F1 Score = 0.8324468085106383
Training data Recall = 0.8496868475991649
Test data Recall = 0.8324468085106383
Training data Precision = 0.9146067415730337
Test data Precision = 0.9260355029585798
0.9103260869565217
Accuracy on Training data :  91.03 %
0.9044516829533116
Accuracy on Test data :  90.45 %


#   naive bayes


new part


In [89]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Function to calculate the mean and variance for each class
def calculate_mean_variance(X, y):
    classes = np.unique(y)
    mean = {}
    var = {}
    priors = {}
    for c in classes:
        X_c = X[y == c]
        mean[c] = X_c.mean(axis=0)
        var[c] = X_c.var(axis=0)
        priors[c] = X_c.shape[0] / float(len(y))
    return mean, var, priors

# Function to calculate the Gaussian probability density function
def gaussian_pdf(x, mean, var):
    numerator = np.exp(-((x - mean) ** 2) / (2 * var))
    denominator = np.sqrt(2 * np.pi * var)
    return numerator / denominator

# Function to calculate the posterior probabilities and predict the class
def predict_single(x, mean, var, priors):
    posteriors = {}
    for c in mean.keys():
        prior = np.log(priors[c])
        posterior = np.sum(np.log(gaussian_pdf(x, mean[c], var[c])))
        posteriors[c] = prior + posterior
    return max(posteriors, key=posteriors.get)

# Function to predict classes for multiple samples
def predict(X, mean, var, priors):
    y_pred = [predict_single(x, mean, var, priors) for x in X]
    return np.array(y_pred)

# Function to calculate accuracy
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

# Main function to load data, train the model, and test it
def main():
    # Load the dataset
    df = pd.read_csv('/content/spambase.csv')

    # Assume the last column is the target variable
    X = df.iloc[:, :-1].values
    y = df.iloc[:, -1].values

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

    # Train the Naive Bayes classifier
    mean, var, priors = calculate_mean_variance(X_train, y_train)
    predictions = predict(X_test, mean, var, priors)

    # Print the accuracy
    print("Naive Bayes classification accuracy:", accuracy(y_test, predictions))
    print(df.head())



if __name__ == "__main__":
    main()


Naive Bayes classification accuracy: 0.8219326818675353
   word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0

<ipython-input-89-3766eebd0f90>:29: RuntimeWarning: divide by zero encountered in log
  posterior = np.sum(np.log(gaussian_pdf(x, mean[c], var[c])))
